apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: lmllp3vdq-python 
  janus-idp.io/tekton: lmllp3vdq-python
  backstage.io/kubernetes-id: lmllp3vdq-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: lmllp3vdq-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml