apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: lmllp3vdq-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lmllp3vdq-python 
  name: lmllp3vdq-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: lmllp3vdq-python 
